### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by muhammad-naderi** [alirezaafkar/SunDate_Picker#3]
Thanks for the hardwork 
it would be nice if you make a maven dependency link for you project so people can import your library with gradle as an online dependency

here is some info:
http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

**Comment by Suall1969** [comment]
@muhammad-naderi  Have you heard of [JitPack] (https://www.jitpack.io/)?
Add remote maven URL in the top level build.gradle file:
```
repositories {
        maven {
            url "https://jitpack.io"
        }
}
```
Then add a library as dependency:
```
dependencies {
         compile 'com.github.alirezaafkar:SunDate_Picker:1.1.0'
}
```

**Comment by alirezaafkar** [comment]
Hey, Sure I'll, but i am really busy right now.
