### ISSUE TITLE
Backward Support, plz...

### ISSUE THREAD

**Issue by javadghane** [alirezaafkar/SunDate_Picker#4]
Hi alireza, thanks for this work.
Is it possible to make this library stable for android 2.3+ ?
the datetimepicker from flavienlaurent is stable for android pre. jellybean... 

great appreciation for this work.

**Comment by Suall1969** [comment]
Yes it is possible, Once I did for the [Ghadr] (https://cafebazaar.ir/app/ir.kaj.ghadr/?l=fa) application.
There's not much effort since it is already using the Support v4 Library.
