### ISSUE TITLE
fragment

### ISSUE THREAD

**Issue by maryhzf** [alirezaafkar/SunDate_Picker#5]
dp.show(getSupportFragmentManager(), "");
this methode does not work in the fragment
please give a sulotion

**Comment by alirezaafkar** [comment]
dp.show(getFragmentManager(), "");

**Comment by maryhzf** [comment]
i try it
but it but it does not work

**Comment by more8028** [comment]
for use in fragment , what code must be replace instead of this:

DatePickerDialog dp = DatePickerDialog.newInstance(
				ExampleActivity.this, id);

because fragment is not an activity , what replace of "ExampleActivity.this"?

**Comment by alirezaafkar** [comment]
@more8028  It doesn't need activity,
use YourFragment.this and implement listener in your fragment

**Comment by muhammad-naderi** [comment]
this is a rewrite of the project with supports of Fragments, and not SupportFragments

https://github.com/muhammad-naderi/SunDatePicker

**Comment by alirezaafkar** [comment]
Come on guys ! What is wrong with you ?
مشکلتون چیه با فرگمنت ؟ مثال زیر رو ببینید
Here is the example of fragment

package com.afkar.sundatepicker;

import android.os.Bundle;
import android.support.v4.app.Fragment;

import java.util.Calendar;

/**
 * Created by Alireza Afkar on 23/11/2015.
 */
public class ExampleFragment extends Fragment implements DatePickerDialog.OnDateSetListener {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        DatePickerDialog.newInstance(ExampleFragment.this, 0).show(getFragmentManager(), "");
    }

    @Override
    public void onDateSet(int id, Calendar calendar, int year, int month, int day) {

    }
}

**Comment by muhammad-naderi** [comment]
مشکل این خطه دوستم

import android.support.v4.app.Fragment;

تو برنامه هایی که برای بعد از
honeycomb
نوشته میشه آدم ترجیح میده از خود 
android.app.Fragment
استفاده کنه تا از supportLibrary

**Comment by alirezaafkar** [comment]
دوست عزیز راجع به فرگمنت ها و اینکه بهتره از کدوم استفاده کنیم تحقیق کنید.

**Comment by more8028** [comment]
مشکل فرگمنت که داشتم حل شد خیلی هم عالی پاسخ دادین اما یه مشکل دیگه من اینه که توی اندروید 2.3.3 کار نمیکنه و فورس ستاپ میده
به نظر شما مشکلش تز کجاست؟

**Comment by alirezaafkar** [comment]
باید ارور رو ببینم، درضمن منتظر نسخه ی جدید باشید
